services:
  app:
    image: oliverdevvm/scannerdevices-app
    container_name: scannerdevices-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/scannerdevicesdb
      - SPRING_DATASOURCE_USERNAME=scanner
      - SPRING_DATASOURCE_PASSWORD=scanner123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    container_name: scannerdevices-db
    environment:
      - MYSQL_ROOT_PASSWORD=scanner123
      - MYSQL_DATABASE=scannerdevicesdb
      - MYSQL_USER=scanner
      - MYSQL_PASSWORD=scanner123
    ports:
        - "3307:3306"
    volumes:
        - db_data:/var/lib/mysql

volumes:
    db_data: