services:
  app:
    build: .
    container_name: scannerdevices-app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0
    container_name: scannerdevices-db
    environment:
      - MYSQL_ROOT_PASSWORD=scanner123
      - MYSQL_DATABASE=scannerdevicesdb
      - MYSQL_USER=scanner
      - MYSQL_PASSWORD=scanner123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: